### ISSUE TITLE
ReportGenerator producing duplicate class rows in summary (cobertura format)

### ISSUE THREAD

**Issue by standsed** [microsoft/codecoverage#124]
In scenario below I am getting duplicate rows (for the same class) in [ReportGenerator](https://github.com/danielpalme/ReportGenerator) summary output

For following code
```
public static class Class1
{
    public static async Task<string> Method1() { return "asdf"; }

    public static async Task<string> Method2<T>(T val) { if (val is string x) { return x; } throw new NotSupportedException(); }

    public static async Task<string> Method3<T, TU>(T val) { return "asdf"; }
}
```
Generated report looks as follows
![image](https://github.com/microsoft/codecoverage/assets/37961304/edbfda4a-19ba-4e64-b6c8-3ed7bc9c730f)

Full project where this is reproduced  [https://github.com/standsed/CodeCoverageRepro](CodeCoverageRepro)

Issue seems arise from class name in produced cobertura xml file.
1st row is from codecoverage file 2nd from coverlet
```
Repro.Class1.&lt;Method3&gt;d__2&lt;T, TU&gt;
Repro.Class1/&lt;Method3&gt;d__2`2

Repro.Class1.&lt;Method2&gt;d__1&lt;T&gt;
Repro.Class1/&lt;Method2&gt;d__1`1

Repro.Class1.&lt;Method1&gt;d__0
Repro.Class1/&lt;Method1&gt;d__0
```
Looks like dot after Class1 breaks some aggregation in ReportGenerator. If I replace this dot with / as in coverlet then report correctly displays just one row for Class1.
[coverlet.txt](https://github.com/user-attachments/files/15802068/coverlet.txt)
[ms_codecoverage.txt](https://github.com/user-attachments/files/15802069/ms_codecoverage.txt)

Since dot is a namespace delimiter this could be something which might need to be adjusted in codecoverage, but let me know if you see this otherwise.

**Comment by fhnaseer** [comment]
Can you please use latest version of reportgenerator and try again?

**Comment by standsed** [comment]
I used latest released reportgenerator version 5.3.6
So unfortunately looks like some cases has slipped by in this fix

**Comment by danielpalme** [comment]
I will have a look in the next days.

**Comment by danielpalme** [comment]
I took a look at those class names.

With version 5.3.6 the part ".<Method1>d__0" is removed from the classes. This results in the following names:

| **Input** | **Output** |
|:--|:--|
| `Repro.Class1.<Method1>d__0` | `Repro.Class1` |
| `Repro.Class1.<Method2>d__1<T>` | `Repro.Class1<T>` |
| `Repro.Class1.<Method3>d__2<T, TU>` | Repro.Class1<T, TU>` |

If I would also remove the generic type `<...>` at the end, the result would be correct in your case.
Reason: In your case the generic type at the end is related to the internal method.

But there are other cases where the generic type at the end is related to the class itself.

Example: `Test.GenericAsyncClass.<MyAsyncMethod>d__0<T>`

Corresponding class:

```csharp
public class GenericAsyncClass<T>
{
  public async Task MyAsyncMethod()
  {
  }
}
```

The only way to distinguish between these two variants is @standsed proposal:

> Since dot is a namespace delimiter this could be something which might need to be adjusted in codecoverage, but let me know if you see this otherwise.

It would be perfect if [Microsoft CodeCoverage](https://github.com/microsoft/codecoverage) could use `/` as a delimiter for nested classes instead of a dot. With that change the distinction is possible.
[Coverlet](https://github.com/coverlet-coverage/coverlet/) is already implemented that way.

With coverlet the class `Test.GenericAsyncClass.<MyAsyncMethod>d__0<T>` becomes `Test.GenericAsyncClass`1/&lt;MyAsyncMethod&gt;d__0`.

**Comment by fhnaseer** [comment]
We keep the names as it is when generated. `.` to represent nested classes. This is also represented in the Code Coverage Results window in the Visual Studio Enterprise. Changing `.` to `/` will be a breaking change and will effect existing users.

```
public static class Class1
{
    [CompilerGenerated]
    private sealed class <Method1>d__0 : IAsyncStateMachine
 ```
https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwKwG5nJQDMmcAbJjOgMIA2AhgM6OJIDey6XmJWFUADkxkAPFlQA+dAFkApgBcAFgHtgcABQBKdG0wB2dACImwAGaHc6AL4Ek3HqX5Coo8VLlLVMEQBUJ6n3QAN3pabV0AS1N0dRDadAjGUgwAD3D9dBTLK3QlACdlAHd0ADtZYoA5ZXkAZQBXAAcG5Tz5WWAAURSAY1kG+QjlEq1s23tiR0xnVzhJGQUVYCJfABp0HwBVf0C49KgDY0YzC2tkKyA
