### ISSUE TITLE
Support for [DoesNotReturn] attribute

### ISSUE THREAD

**Issue by DwayneNeed** [microsoft/codecoverage#58]
Net introduced the [DoesNotReturn] and [DoesNotReturnIf] attributes are part of nullability static analysis: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis

These are often used for "throw helpers". Calling these methods can result in the dreaded "uncovered curly brace".

Recently, coverlet added support for this: https://github.com/coverlet-coverage/coverlet/issues/898

Can we get this added to the Visual Studio 2022 Enterprise code coverage tool as well?

**Comment by mariam-abdulla** [comment]
@DwayneNeed Hi,

We added support for [DoesNotReturn] attribute.
You may find this update in the latest update in [dotnet-coverage](https://www.nuget.org/packages/dotnet-coverage/17.10.2).
Also, it will be available in the next Visual Studio release (17.10).

**Comment by mariam-abdulla** [comment]
[DoesNotReturnIf] attribute is unsupported because there is no way for us to support this.

Please note that [DoesNotReturn] attribute is not supported across dlls at the moment, we will be supporting this later on.
However, in the meantime there is a workaround which is adding a wrapper method with [DoesNotReturn] attribute which calls the method in the other dll and let the caller call this method instead. Also, you should add [ExcludeFromCodeCoverage] for this method.

Please find an example below:
```
a.dll
bool  Method
{
	ThrowWrapper();
}
 
[ExcludeFromCodeCoverage]
[DoesNotReturn]
ThrowWrapper()
{
	Throw();
}
 
b.dll
[DoesNotReturn] Throw()
{
	throw new Exeception();
}
```

**Comment by mariam-abdulla** [comment]
@DwayneNeed, We supported [DoesNotReturn] attribute across different dlls.

We have 3 options related to [DoesNotReturn] attribute which can be controlled from the runsettings file, under data collector configuration section. Please use:

1. `<DoesNotReturnAttribute>None</DoesNotReturnAttribute>` if you wish to disable this feature.
2. `<DoesNotReturnAttribute>SameAssembly</DoesNotReturnAttribute>` if you wish to enable it in same assembly.
3. `<DoesNotReturnAttribute>AllAssemblies</DoesNotReturnAttribute>` if you wish to enable it cross assemblies.

Please note the 2nd option (`SameAssembly`) is enabled by default.

Also, there will be a new release of dotnet-coverage soon.
